# fly.toml app configuration file generated for connect-people on 2023-06-12T01:12:42+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "connect-people"
primary_region = "nrt"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  image = "wibu009/connect_people:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  Cloudinary__ApiKey = "831276283983712"
  Cloudinary__CloudName = "wibu009"
  Facebook__AppId = "120699144314450"
  SendGrid__User = "Connect People Events"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
